services:
  postgres:
    build:
      context: .
      network: host
      args:
        HTTP_PROXY: "${BUILD_PROXY:-}"
        HTTPS_PROXY: "${BUILD_PROXY:-}"
    networks:
      - proxy-net
    container_name: pg_semantic
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semantic_test
      HTTP_PROXY: "${XRAY_URL:-http://xray:1087}"
      HTTPS_PROXY: "${XRAY_URL:-http://xray:1087}"
      NO_PROXY: "${NO_PROXY_URL:-localhost,127.0.0.1,*.feishu.cn,*.larksuite.com,*.larkoffice.com,open.feishu.cn,open.larksuite.com,bigmodel.cn,open.bigmodel.cn,api.minimaxi.com}"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./.env:/etc/pg_semantic/.env:ro
      - /home/yuanjian/tmp_data/:/tmp/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  proxy-net:
    external: true